### ISSUE TITLE
Is there a way to set highlighting options in the SearchOptions with Lettusearch?

### ISSUE THREAD

**Issue by elizabetht** [RediSearch/lettusearch#1]
I was looking to get the search query highlighted in the resulting documents

**Comment by jruaux** [comment]
Thanks for your request. I just added highlighting to release 1.2.0

**Comment by elizabetht** [comment]
Great! Is there a snapshot version for 1.2.0 I can try highlighting with?

**Comment by jruaux** [comment]
You can find 1.2.0 in Maven central or you could build the 1.2.1-SNAPSHOT version from github
