### ISSUE TITLE
How to search with filters and by document id?

### ISSUE THREAD

**Issue by kalyashov** [RediSearch/lettusearch#12]
Hi, I want to use [INKEYS ](https://oss.redislabs.com/redisearch/Commands/#ftsearch) parameter to restrict RediSearch results by a document ID.

Example in redis-cli:
`FT.SEARCH SAMPLE_INDEX  "(@channels:{test})" INKEYS 1 4`

Is there any way to search like that with lettusearch? I don't see that it is possible to specify this parameter in **com.redislabs.lettusearch.search.SearchOptions**

**Comment by jruaux** [comment]
You're correct, INKEYS is not supported. I will add it shortly.

**Comment by kalyashov** [comment]
@jruax Thanks! I'll wait for this feature

**Comment by jruaux** [comment]
Just released v2.2.1 that includes support for INKEYS
