### ISSUE TITLE
DocumentBuillder requires String payload

### ISSUE THREAD

**Issue by rnbWarden** [RediSearch/lettusearch#14]
with this commit : 02f72add404e7aecf6d26efd4b386751baa2b65b you removed the functionality of the K,V payload generics on the document. Any objections to changing the DocumentBuilder.fields and field() to take a K,V rather than String, String?

**Comment by jruaux** [comment]
No objections. I just pushed release v2.3.2 with generics builder

**Comment by rnbWarden** [comment]
Thanks!
