### ISSUE TITLE
SortBy with multi-fields allowed but not supported

### ISSUE THREAD

**Issue by lpellegr** [RediSearch/lettusearch#15]
While using this client library, I noticed that you can create a FT.SEARCH query with a multi-fields SORTBY with no errors whereas the backend does not support it.

Here is an example:

```java
 final SearchResults<String, String> searchResult = connection.sync().search(
                "post", queryString,
                SearchOptions.builder()
                        .limit(Limit.builder().num(limit).build())
                        .sortBy(SortBy.builder()
                                .field("pinned").direction(Direction.Descending)
                                .field("publicationTime").direction(Direction.Descending)
                                .field("updateTime").direction(Direction.Descending).build()).build());
```

It seems that only the last SortBy field is considered.

There is maybe a reason I am not aware of, but as a user, I was expecting a compilation error or at least an error at runtime.

**Comment by jruaux** [comment]
SortBy builder only takes one field. The multiple calls to field("...") are just setting the field property multiple times.

**Comment by lpellegr** [comment]
@jruaux Yes, that's what I noticed after spending some time to understand that `FT.SEARCH `supports `SORTBY` on a single field only. Since the backend, does not support multi-field `SORTBY`, why are you allowing such a construction?

If you look at the construction with FT.AGGREGATE, consecutive calls are not overriding previous ones. This makes sense since FT.AGGREGATE supports multi-field SORTBY but the difference of behavior might look confusing for new users:

```
Sort.builder()
    .property(SortProperty.builder().property("pinned").order(Order.Desc).build())
    .property(SortProperty.builder().property("publicationTime").order(Order.Desc).build())
    .property(SortProperty.builder().property("updateTime").order(Order.Desc).build())
```

It was just to say preventing the construction with FT.SEARCH or at least to document the method could save time for new users. Feel free to close the issue if it makes no sense.

**Comment by jruaux** [comment]
This is the expected behavior for the builder pattern. Look at how collections are handled by Lombok which is what I use here to generate these builders: https://www.baeldung.com/lombok-builder-singular
