### ISSUE TITLE
getInfo in RediSearchUtils does not work with RediSearch 2.0

### ISSUE THREAD

**Issue by koreykiran** [RediSearch/lettusearch#37]
Hi Team,

The getInfo method in RediSearchUtils does not work with RediSearch 2.0 module. 
It throws the below exception.
**Exception:java.lang.String cannot be cast to java.lang.Double**

Thank you,

**Comment by koreykiran** [comment]
Hi Team,
any updates on this?

Thank you.

**Comment by jruaux** [comment]
Hi,

Sorry for the delay. This is a known issue that was introduced with the upgrade to Lettuce 6.0. See here for more details: #33

**Comment by koreykiran** [comment]
Hi,

Thank you for the update, is there timeframe for the fix?

**Comment by jruaux** [comment]
Sorry this is dependent on next Lettuce release which I don't think has a date set. I'll keep monitoring the lettuce project and update lettusearch as soon as they release the fix

**Comment by jruaux** [comment]
@koreykiran this issue was fixed in release 2.5.0

**Comment by koreykiran** [comment]
Thank you for the update.

**Comment by koreykiran** [comment]
The connection pooling does not seem to work, could you please update the documentation for the connection pooling.

**Comment by jruaux** [comment]
What problem are you seeing?
