### ISSUE TITLE
RediSearchReactiveCommands<String, Object> not compiling

### ISSUE THREAD

**Issue by autocorrectoff** [RediSearch/lettusearch#4]
RediSearchReactiveCommands<String, Object> doesn't compile. The exception is Incompatible types: RediSearchReactiveCommands<String, String> required. Is it not possible to specify other than a String as value?

**Comment by jruaux** [comment]
Hi,

You will need to specify a codec in order for LettuSearch to know how to de/serialize your objects. Here is the part of the Lettuce documentation that covers how to use codecs:  https://github.com/lettuce-io/lettuce-core/wiki/Codecs

Thanks,
Julien
