### ISSUE TITLE
NLP when using sugget method

### ISSUE THREAD

**Issue by giridharkannan** [RediSearch/lettusearch#49]
When using two argument sugget method

`List<Suggestion<V>> sugget(K key, V prefix);` instead of 
`List<Suggestion<V>> sugget(K key, V prefix, SuggetOptions options);`

Default SuggetOptions is not passed, which results in NLP

**Comment by jruaux** [comment]
Thanks for reporting the issue. This has been fixed in v2.6.1 and v3.0.0
