### ISSUE TITLE
Transformation(Apply) for aggregation is not working.

### ISSUE THREAD

**Issue by Ananda2126** [RediSearch/lettusearch#52]
Transformation(Apply) for aggregation is not working.

Getting error as : Value was not found in result (not a hard error) while running the below expression.
"format(\\"%s\\", @field)"

**Comment by jruaux** [comment]
This seems to be a RediSearch issue rather than a LettuSearch client issue. Can you see if this is what you are experiencing: https://github.com/RediSearch/RediSearch/issues/1265
