### ISSUE TITLE
ToList reducer is not returning results as expected. 

### ISSUE THREAD

**Issue by Ananda2126** [RediSearch/lettusearch#53]
When running below query in redis cli: 
FT.AGGREGATE <index_name>* GROUPBY 1 @field REDUCE TOLIST 1 @field1 as list REDUCE COUNT 0 as count
Result:
1) (integer) 1
2) 1)"field"
    2)"value"
3) "list"
4) 1)"field1_value1"
    2)"field1_value2"
5) "count"
6) "5"

But when we run through lettusearch : 
Result: (AggregateResults)
 {
    "field": "value",
    "list": "field1_value1"
    "field1_value2": "count"
  }
It should be:
 {
    "field": "value",
    "list": "field1_value1","field1_value2"
    "count": 5
  }

**Comment by Ananda2126** [comment]
Any update or any work around for this issue?

**Comment by jruaux** [comment]
Sorry for the delay and thank you for reporting this issue. It has been fixed in release 3.1.1
