### ISSUE TITLE
Empty AggregateResults if at least one ToList reducer is empty

### ISSUE THREAD

**Issue by griand** [RediSearch/lettusearch#64]
Steps for reproduce:
`FT.CREATE idx ON HASH PREFIX 1 my_prefix: SCHEMA category TAG SORTABLE color TAG SORTABLE size TAG SORTABLE`
`FT.AGGREGATE idx @color:{red|blue} GROUPBY 1 @category REDUCE TOLIST 1 @color AS color REDUCE TOLIST 1 @size AS size`

**Bug condition:** if the search request `@color:{red|blue}` returns no data for ToList reducer for `size` field then lettusearch api return empty AggregateResults (but getCount() method return value > 0);

**Expected behavior:** return empty list for empty ToList reducer.

Redis cli response for above query:
```
1) (integer) 1
2) 1) "category"
   2) "31"
   3) "color"
   4) 1) "red"
   5) "size"
   6) (empty list or set)
```

```
lettuSearchConnection.aggregate("idx", "@color:{red|blue}",
                com.redislabs.lettusearch.AggregateOptions.builder()
                        .groupBy(List.of("category"), com.redislabs.lettusearch.AggregateOptions.Operation.GroupBy.Reducer
                                        .ToList.builder().property("color").as("color").build(),
                                com.redislabs.lettusearch.AggregateOptions.Operation.GroupBy.Reducer
                                        .ToList.builder().property("size").as("size").build()
                        ).build()
        ).subscribe(ar -> {
            long count = ar.getCount(); <<<  count = 1
            Map<String, Object> map = ar.get(0);  <<< java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
        });
```

Redis server 6.2.3
Redisearch 2.0.9
Lettusearch 3.1.2

**Comment by jruaux** [comment]
This was added to LettuceMod (new home for lettusearch functionality)
