### ISSUE TITLE
SearchOptions without inKeys, inFields and returnFields results in Nullpointer exception.

### ISSUE THREAD

**Issue by Ananda2126** [RediSearch/lettusearch#66]
SearchOptions without inKeys, inFields and returnFields results in Nullpointer exception.

if (!this.inKeys.isEmpty()) , if (!this.inFields.isEmpty()) and if (!this.returnFields.isEmpty()) in SearchOptions.java file will result nullpointer exception if fields are null.

Fix:
if (this.inKeys != null && !this.inKeys.isEmpty()) 
if (this.inFields != null && !this.inFields.isEmpty())
if (this.returnFields != null && !this.returnFields.isEmpty())

**Comment by jruaux** [comment]
Thanks, this was fixed in https://github.com/redis-developer/lettucemod/commit/8ac19c55b9b50789293bd6a1cc330b1ae3c38703
