### ISSUE TITLE
SearchOptions with noContent set as true returns array of empty objects.

### ISSUE THREAD

**Issue by Ananda2126** [RediSearch/lettusearch#68]
SearchOptions with noContent set as true returns array of empty objects.

But as per redis documentation it should return list of document ids. 
NOCONTENT : If it appears after the query, we only return the document ids and not the content. This is useful if RediSearch is only an index on an external document collection

**Comment by jruaux** [comment]
LettuSearch now lives at https://github.com/redis-developer/lettucemod
The issue does not seem to happen in LettuceMod (added this [testcase](166d61482ec97cc7dc59522ee30ef1db5f5abbdc))
