### ISSUE TITLE
AGGREGATE filter not respecting codec

### ISSUE THREAD

**Issue by anderslangballe** [RediSearch/lettusearch#69]
Recently, Redisearch added contains filters on aggregate queries, e.g.:
`FT.AGGREGATE idx * FILTER "contains(@name, 'åæø')"`

However, when using aggregate queries with lettusearch, it seems that the `StringCodec` is not respected unlike when using a select string.

More specifically, the filter string will be added with `RediSearchCommandArgs::add`, whereas the values of select strings are added with `RediSearchCommandArgs::addValue`. The former does not seem to respect the `StringCodec` used. As such, the query I gave above is not possible with lettusearch as far as I can tell since UTF-8 is used.

**Comment by jruaux** [comment]
Fixed in lettucemod project
