### ISSUE TITLE
Not valid CommandArgs query for Russian text search

### ISSUE THREAD

**Issue by nemodeveloper** [RediSearch/lettusearch#7]
Hello, Im Aleksey
Im start use library and find interesting "bug"
When im try search like this (Im use kotlin)

val result = redis.rediSearchReactiveCommands.search(
                indexName,
                filters.joinToString(" "),
                SearchOptions.builder()
                        .language(Language.Russian.name.toLowerCase())
                        .limit(Limit.builder()
                                .num(pageable.pageSize.toLong())
                                .offset(pageable.offset)
                                .build())
                        .returnFields(RETURN_CACHE_FIELDS)
                        .build())
                .awaitFirst()

Filters contains search with Russian chars 

Im use UTF-8 Codec for init 
RediSearchClient.create(lettuceConnectionFactory.clientResources, redisURI)
                .connect(StringCodec.UTF8!!, redisURI).reactive()

So when query go to RediSearch query  string come "not valid" and redis return empty results

Im do some debug and find place in RediSearchCommandBuilder 
method - public Command<K, V, SearchResults<K, V>> search(String index, String query, SearchOptions options)

code line with bug - RediSearchCommandArgs<K, V> commandArgs = createArgs(index);
		commandArgs.add(query);

when call - commandArgs.add(query); 
its just decode without CODEC which use in init and go to not valid for redisearch

I think this line must call  - commandArgs.addKey(query);
Im do my custom copy paste code from this and its work fine!
Because commandArgs.addKey(query); decode value string with Codec!

Can you fix this or say why Russian query not correct work with this library?
Im can do PR for this or you fix it itself?) 

Ty its very need for me

**Comment by jruaux** [comment]
Hi Aleksey,

Thank you for reporting this issue. You are right that the add(query) call should be using the codec. However I'm not sure if it should be using the key encoder or the value encoder (K and V types respectively in RedisCodec<K, V>).

What do you think?

Thanks,
Julien

**Comment by nemodeveloper** [comment]
I think that addValue is better because query text its not key its value for query search command
Example in UTF-8 codec decodeKey and decodeValue equals  but for  more  support different cases it should be addValue

And yet one moment when call this method in RediSearchCommandBuilder
private RediSearchCommandArgs<K, V> createArgs(String index) {
		return new RediSearchCommandArgs<>(codec).add(index);
	}
Its also should call addKey/addValue because index name its key/value for SEARCH command

Thanks

**Comment by nemodeveloper** [comment]
@jruaux when should waiting fix this?

**Comment by jruaux** [comment]
Hi, I just released version 2.1.0 with K for index and V for query. Let me know if that works for you.

**Comment by nemodeveloper** [comment]
@jruaux , im check it, now its work fine
Ty very much!)

**Comment by jruaux** [comment]
Great, thanks for validating the fix. I'll close the issue.
