### ISSUE TITLE
SearchOptions with Scorer

### ISSUE THREAD

**Issue by kalyashov** [RediSearch/lettusearch#70]
Hi!
Is it possible to add support change default scorer in SearchOptions?
https://oss.redis.com/redisearch/Scoring/

**Comment by jruaux** [comment]
LettuSearch is now deprecated in favor of LettuceMod which supports setting the scorer: https://github.com/redis-developer/lettucemod

**Comment by kalyashov** [comment]
@jruaux thanks, I looked at this library, it is more suitable for RediSearch 2.x

The problem is that at the moment our project uses RediSearch 1.x and lettusearch 2.5.0, we cannot migrate our production to RediSearch 2.x in the near future, but at the moment we need to set a SCORER when searching.

Is it possible to add support change default scorer and release of the lettusearch 2.6.2?
