### ISSUE TITLE
ERR unknown command `FT.CREATE`

### ISSUE THREAD

**Issue by gyana12** [RediSearch/lettusearch#8]
while creating an index getting error 

> ERR unknown command `FT.CREATE`

`redis-cli --cluster call 127.0.0.1:30001 FT.CREATE myIdx SCHEMA title TEXT WEIGHT 5.0 body TEXT url TEXT value NUMERIC`

i tried to install the redis search module using below command, but no success.
`redis-cli --cluster call 127.0.0.1:30001 MODULE load redisearch.so OPT1 OPT2`

**Comment by jruaux** [comment]
I think your question is about RediSearch, not LettuSearch. Can you post your question in the RediSearch mailing list mentioned here? https://github.com/RediSearch/RediSearch

**Comment by gyana12** [comment]
As i was using LettuceSearch API to create the index, i thought it is suitable place. Thanks for information.
